name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            before: make download install-ta-lib
          # - os: macos-11
          #   before: brew install ta-lib
          - os: windows-latest
            before: .\temp.ps1
            # env:
            #   DEPS_PATH: ${{ github.workspace }}/dependencies
            #   TA_INCLUDE_PATH: ${{ github.workspace }}/dependencies/include
            #   TA_LIBRARY_PATH: ${{ github.workspace }}/dependencies/lib

    steps:
      - uses: actions/checkout@v3

      # Used to host cibuildwheel
      - uses: actions/setup-python@v3

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.13.1

      - name: Install ta-lib linux
        if: runner.os == 'Linux'
        run: make download install-ta-lib
      
      # - name: Build wheels
      #   run: python -m cibuildwheel --output-dir wheelhouse
      #   env:
      #     CIBW_ARCHS_LINUX: native aarch64
      #     CIBW_BEFORE_ALL: ${{ matrix.before }}
      #     CIBW_BEFORE_BUILD: pip install -r requirements.txt
      #     CIBW_SKIP: cp36-* cp37-* pp37-* *musllinux*

      # - uses: actions/upload-artifact@v3
      #   with:
      #     path: ./wheelhouse/*.whl
      
      # - name: upload to PyPI
      #   run: |
      #     pip install twine && 
      #     twine upload wheelhouse/*.whl -u __token__ \
      #     -p ${{ secrets.TWINE_PASSWORD }}  --verbose  --skip-existing
